---
title: "Project-1"
subtitle: "project sunroof"
author: "Bradley Reardon, Pranay Bhakthula, Baldur Hua, Jichong Wu, Qinyuan Xing"
date: "today"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
---
  
```{r basic, include=F}
# use this function to conveniently load libraries and work smoothly with knitting
# can add quietly=T option to the require() function
loadPkg = function(x) { if (!require(x,character.only=T, quietly =T)) { install.packages(x,dep=T,repos="http://cran.us.r-project.org"); if(!require(x,character.only=T)) stop("Package not found") } }

# unload/detact package when done using it
unloadPkg = function(pkg, character.only = FALSE) { 
  if(!character.only) { pkg <- as.character(substitute(pkg)) } 
  search_item <- paste("package", pkg,sep = ":") 
  while(search_item %in% search()) { detach(search_item, unload = TRUE, character.only = TRUE) } 
}
```

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

```{r xkablesummary}
loadPkg("xtable")
loadPkg("kableExtra")
loadPkg("stringi")

xkabledply = function(modelsmmrytable, title="Table", digits = 4, pos="left", bso="striped") { 
  #' Combining base::summary, xtable, and kableExtra, to easily display model summary. 
  #' wrapper for the base::summary function on model objects
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param modelsmmrytable This can be a generic table, a model object such as lm(), or the summary of a model object summary(lm()) 
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @return HTML table for display
  #' @examples
  #' library("xtable")
  #' library("kableExtra")
  #' xkabledply( df, title="Table testing", pos="left", bso="hover" )
  modelsmmrytable %>%
    xtable() %>% 
    kable(caption = title, digits = digits) %>%
    kable_styling(bootstrap_options = bso, full_width = FALSE, position = pos)
}

xkablesummary = function(df, title="Table: Statistics summary.", digits = 4, pos="left", bso="striped") { 
  #' Combining base::summary, xtable, and kableExtra, to easily display numeric variable summary of dataframes. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param df The dataframe.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @return The HTML summary table for display, or for knitr to process into other formats 
  #' @examples
  #' xkablesummary( faraway::ozone )
  #' xkablesummary( ISLR::Hitters, title="Five number summary", pos="left", bso="hover"  )
  
  s = summary(df) %>%
    apply( 2, function(x) stringr::str_remove_all(x,c("Min.\\s*:\\s*","1st Qu.\\s*:\\s*","Median\\s*:\\s*","Mean\\s*:\\s*","3rd Qu.\\s*:\\s*","Max.\\s*:\\s*")) ) %>% # replace all leading words
    apply( 2, function(x) stringr::str_trim(x, "right")) # trim trailing spaces left
  
  colnames(s) <- stringr::str_trim(colnames(s))
  
  if ( dim(s)[1] ==6 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max') 
  } else if ( dim(s)[1] ==7 ) { rownames(s) <- c('Min','Q1','Median','Mean','Q3','Max','NA') }
  
  xkabledply(s, title=title, digits = digits, pos=pos, bso=bso )
}

xkablevif = function(model, title="VIFs of the model", digits = 3, pos="left", bso="striped", wide=FALSE) { 
  #' Combining faraway::vif, xtable, and kableExtra, to easily display numeric summary of VIFs for a model. 
  #' ELo 202004 GWU DATS
  #' version 1.2
  #' @param model The lm or compatible model object.
  #' @param title Title of table. 
  #' @param digits Number of digits to display
  #' @param pos Position of table, c("left","center","right") 
  #' @param bso bootstrap_options = c("basic", "striped", "bordered", "hover", "condensed", "responsive")
  #' @param wide print table in long (FALSE) format or wide (TRUE) format
  #' @return The HTML summary table of the VIFs for a model for display, or for knitr to process into other formats 
  #' @examples
  #' xkablevif( lm(Salary~Hits+RBI, data=ISLR::Hitters, wide=T ) )
  
  vifs = table( names(model$coefficients)[2:length(model$coefficients)] ) # remove intercept to set column names
  vifs[] = faraway::vif(model) # set the values
  if (wide) { vifs <- t(vifs) }
  xkabledply( vifs, title=title, digits = digits, pos=pos, bso=bso )
}

```

# Step-1 - clean the data.  
Read city and state csv files as a data frame and remove unnecessary columns.  

```{r q1}
citydf <- data.frame(read.csv('city.csv'))
statedf<-data.frame(read.csv('state.csv'))

citydf1<-subset(citydf,select = -c(number_of_panels_median, yearly_sunlight_kwh_median, install_size_kw_buckets_json))

statedf1<-subset(statedf,select = -c(number_of_panels_median, yearly_sunlight_kwh_median, install_size_kw_buckets_json))

```
Renaming the long column names to short names.  
```{r change names in citydf1}
names(citydf1)[names(citydf1)=="yearly_sunlight_kwh_kw_threshold_avg"]<- "threshold_kw_avg"

names(citydf1)[names(citydf1)=="number_of_panels_n"]<- "panels_north"
names(citydf1)[names(citydf1)=="number_of_panels_s"]<- "panels_south"
names(citydf1)[names(citydf1)=="number_of_panels_e"]<- "panels_east"
names(citydf1)[names(citydf1)=="number_of_panels_w"]<- "panels_west"
names(citydf1)[names(citydf1)=="number_of_panels_f"]<- "panels_flat"
names(citydf1)[names(citydf1)=="number_of_panels_total"]<- "panels_total"

names(citydf1)[names(citydf1)=="yearly_sunlight_kwh_n"]<- "sunlight_north"
names(citydf1)[names(citydf1)=="yearly_sunlight_kwh_s"]<- "sunlight_south"
names(citydf1)[names(citydf1)=="yearly_sunlight_kwh_e"]<- "sunlight_east"
names(citydf1)[names(citydf1)=="yearly_sunlight_kwh_w"]<- "sunlight_west"
names(citydf1)[names(citydf1)=="yearly_sunlight_kwh_f"]<- "sunlight_flat"
names(citydf1)[names(citydf1)=="yearly_sunlight_kwh_total"]<- "sunlight_total"

names(citydf1)[names(citydf1)=="carbon_offset_metric_tons"]<- "carbon_offset"
names(citydf1)[names(citydf1)=="existing_installs_count"]<- "count_existing"

```

```{r change names in statedf1}
names(statedf1)[names(statedf1)=="yearly_sunlight_kwh_kw_threshold_avg"]<- "threshold_kw_avg"

names(statedf1)[names(statedf1)=="number_of_panels_n"]<- "panels_north"
names(statedf1)[names(statedf1)=="number_of_panels_s"]<- "panels_south"
names(statedf1)[names(statedf1)=="number_of_panels_e"]<- "panels_east"
names(statedf1)[names(statedf1)=="number_of_panels_w"]<- "panels_west"
names(statedf1)[names(statedf1)=="number_of_panels_f"]<- "panels_flat"
names(statedf1)[names(statedf1)=="number_of_panels_total"]<- "panels_total"

names(statedf1)[names(statedf1)=="yearly_sunlight_kwh_n"]<- "sunlight_north"
names(statedf1)[names(statedf1)=="yearly_sunlight_kwh_s"]<- "sunlight_south"
names(statedf1)[names(statedf1)=="yearly_sunlight_kwh_e"]<- "sunlight_east"
names(statedf1)[names(statedf1)=="yearly_sunlight_kwh_w"]<- "sunlight_west"
names(statedf1)[names(statedf1)=="yearly_sunlight_kwh_f"]<- "sunlight_flat"
names(statedf1)[names(statedf1)=="yearly_sunlight_kwh_total"]<- "sunlight_total"

names(statedf1)[names(statedf1)=="carbon_offset_metric_tons"]<- "carbon_offset"
names(statedf1)[names(statedf1)=="existing_installs_count"]<- "count_existing"

```
Changing the datatypes for necessary columns.   
```{r change datatype}
citydf1$threshold_kw_avg<-as.numeric(citydf1$threshold_kw_avg)
citydf1$panels_total<-as.numeric(citydf1$panels_total)
citydf1$kw_median<-as.numeric(citydf1$kw_median)
citydf1$kw_total<-as.numeric(citydf1$kw_total)
citydf1$sunlight_total<-as.numeric(citydf1$sunlight_total)

statedf1$threshold_kw_avg<-as.numeric(statedf1$threshold_kw_avg)
statedf1$panels_total<-as.numeric(statedf1$panels_total)
statedf1$kw_median<-as.numeric(statedf1$kw_median)
statedf1$kw_total<-as.numeric(statedf1$kw_total)
statedf1$sunlight_total<-as.numeric(statedf1$sunlight_total)
```


```{r EDA_basicstats, results=T}

xkablesummary(citydf1,title = "summary of citydf1")
xkablesummary(statedf1,title = "summary of statedf1")
```







